# Overview: Numpy and Math
- Lists, tuples and dicts
- Vectors, matrices and their implementation in numpy
- Simple linalg
- references and copies (asarray vs array and list<> with operator*

# Iterables
Iterables are sequence objects. They are variables that store not a single value but multiples of them. In a fixed order. 

## List
Ordered collection of elements, can be of different type, duplicates possible

In [1]:
[1, 2, 3]

[1, 2, 3]

In [2]:
["a", "b"]

['a', 'b']

In [3]:
# append via +
[1, 2] + [3, 5]

[1, 2, 3, 5]

In [6]:

# or via append command
a = []
for i in range(3):
    a.append(i)
    
a

[0, 1, 2]

In [8]:
a = [1, 2, 3]

# acces via brackts
a[0], a[2]

(1, 3)

In [10]:
# index starts at 0
a[3]

IndexError: list index out of range

## set
collection of elements, ordered via lexical sort, data types can mix, no duplicates!

In [11]:
{1, 5, 6, 2, 1}

{1, 2, 5, 6}

## tuple
ordered collection, data types can mix, duplicates possible. Immutable!

In [12]:
(1, 5, 6, 2, 1)

(1, 5, 6, 2, 1)

tuples can be unpacked using the comma operator!

In [19]:
a, b = (1, test)

In [20]:
a

1

In [21]:
b

'tet'

In [22]:
a = 2, 4
a

(2, 4)

## dict
dictionary objects. Contains pairs of keys and values (unordered). Keys must be immutable objects (tuples ok, list nok!). data types for keys and values can mix

In [13]:
{"a":1, "b":2}

{'a': 1, 'b': 2}

In [14]:
a = {}

a["a"] = 1
a["b"] =  5

a

{'a': 1, 'b': 5}

In [25]:
a = {}

# enumerate(<iterable>) yields the elements of the iterable in a tuple together with the index
for i, x in enumerate(range(3, 6)):
    a[i] = x
    
a

{0: 3, 1: 4, 2: 5}

you can access the keys, values separately or together via items 

In [26]:
a = {"a":1, "b":2, "c": 3}

In [27]:
a.keys()

dict_keys(['a', 'b', 'c'])

In [28]:
a.values()

dict_values([1, 2, 3])

In [29]:
a.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [30]:
for k, v in a.items():
    print(f"{k}: {v}")

a: 1
b: 2
c: 3


# Modules 
modules are imported using import

# Numpy

In [31]:
import numpy as np

In [32]:
np.array([1, 2, 3])

array([1, 2, 3])

In [34]:
# like range, but returns a numpy array
np.arange(4)

array([0, 1, 2, 3])

In [35]:

a = np.array([1, 2, 3])
a.shape

(3,)

In [37]:
b = np.arange(3)
b.shape

(3,)

# Simple Vector math 

In [41]:
a

array([1, 2, 3])

In [42]:
b

array([0, 1, 2])

In [38]:
a + b

array([1, 3, 5])

In [39]:
a * b

array([0, 2, 6])

In [40]:
np.dot(a, b)

8

# Matrices 

In [46]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9]
])

In [47]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
M.shape

(3, 3)

In [48]:
np.dot(M, a)

array([14, 32, 50])

In [49]:
np.ones(3)

array([1., 1., 1.])

In [51]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [54]:
np.diag(M)

array([1, 5, 9])

In [56]:
np.eigvals(M)

AttributeError: module 'numpy' has no attribute 'eigvals'

### Exercise
build a 9 x9 matrix, that has 1s at all values at the edges but zeros elsewhere. 

### Exercise
build a 4 x4 matrix a 2x2 block of ones in the center and zeros elsewhere

### Calculate the eigenvalues of any pauli matrix
https://en.wikipedia.org/wiki/Pauli_matrices