# Overview: Numpy and Math
- Lists, tuples and dicts
- Vectors, matrices and their implementation in numpy
- Simple linalg
- references and copies (asarray vs array and list<> with operator*

# Iterables
Iterables are sequence objects. They are variables that store not a single value but multiples of them. In a fixed order. 

## List
Ordered collection of elements, can be of different type, duplicates possible

In [2]:
[1, 2, 3]

[1, 2, 3]

In [3]:
["a", "b"]

['a', 'b']

In [4]:
# append via +
[1, 2] + [3, 5]

[1, 2, 3, 5]

In [5]:

# or via append command
a = []
for i in range(3):
    a.append(i)
    
a

[0, 1, 2]

In [6]:
a = [1, 2, 3]

# acces via brackts
a[0], a[2]

(1, 3)

In [7]:
# index starts at 0
a[3]

IndexError: list index out of range

## set
collection of elements, ordered via lexical sort, data types can mix, no duplicates!

In [8]:
{1, 5, 6, 2, 1}

{1, 2, 5, 6}

## tuple
ordered collection, data types can mix, duplicates possible. Immutable!

In [9]:
(1, 5, 6, 2, 1)

(1, 5, 6, 2, 1)

tuples can be unpacked using the comma operator!

In [10]:
a, b = (1, test)

NameError: name 'test' is not defined

In [11]:
a

[1, 2, 3]

In [12]:
b

NameError: name 'b' is not defined

In [13]:
a = 2, 4
a

(2, 4)

## dict
dictionary objects. Contains pairs of keys and values (unordered). Keys must be immutable objects (tuples ok, list nok!). data types for keys and values can mix

In [14]:
{"a":1, "b":2}

{'a': 1, 'b': 2}

In [15]:
a = {}

a["a"] = 1
a["b"] =  5

a

{'a': 1, 'b': 5}

In [16]:
a = {}

# enumerate(<iterable>) yields the elements of the iterable in a tuple together with the index
for i, x in enumerate(range(3, 6)):
    a[i] = x
    
a

{0: 3, 1: 4, 2: 5}

you can access the keys, values separately or together via items 

In [17]:
a = {"a":1, "b":2, "c": 3}

In [18]:
a.keys()

dict_keys(['a', 'b', 'c'])

In [19]:
a.values()

dict_values([1, 2, 3])

In [20]:
a.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [21]:
for k, v in a.items():
    print(f"{k}: {v}")

a: 1
b: 2
c: 3


# Modules 
modules are imported using import

# Numpy

In [22]:
import numpy as np

In [23]:
np.array([1, 2, 3])

array([1, 2, 3])

In [24]:
# like range, but returns a numpy array
np.arange(4)

array([0, 1, 2, 3])

In [25]:

a = np.array([1, 2, 3])
a.shape

(3,)

In [26]:
b = np.arange(3)
b.shape

(3,)

# Simple Vector math 

In [27]:
a

array([1, 2, 3])

In [28]:
b

array([0, 1, 2])

In [29]:
a + b

array([1, 3, 5])

In [30]:
a * b

array([0, 2, 6])

In [31]:
np.dot(a, b)

8

# Matrices 

In [32]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9]
])

In [33]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
M.shape

(3, 3)

In [35]:
np.dot(M, a)

array([14, 32, 50])

In [36]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [40]:
np.diag(M)

array([1, 5, 9])

In [41]:
np.linalg.eigvals(M)

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

In [42]:
np.linalg.eigvals(np.eye(3))

array([1., 1., 1.])

## Indexing and Slicing of Numpy arrays

In [63]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [64]:
a[3]

3

In [65]:
a[2:4]

array([2, 3])

In [66]:
# you can set elements in the array like this
a[2:4] = 10
a

array([ 0,  1, 10, 10,  4,  5])

In [67]:
# you can set elements in the array like this
a[2:4] = np.array([1000, 1000])
a

array([   0,    1, 1000, 1000,    4,    5])

In [68]:
# you can also set single elements
a[2] = -20
a

array([   0,    1,  -20, 1000,    4,    5])

## Logical Indexing

You can very easily create arrays with logical values

In [69]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
L = a > 4
L

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
# '%' is the modulo operator
# https://en.wikipedia.org/wiki/Modulo_operation
L = a % 2
L

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

Logical array can be used as in indexing mask. All values that correspond to elements in the logical array that are True can be accessed with the logical array, like so

In [72]:
a[L]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [73]:
a[L] = 100
a

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9])

### Exercise
build a 9 x9 matrix, that has 1s at all values at the edges but zeros elsewhere. 

### Exercise
build a 4 x4 matrix a 2x2 block of ones in the center and zeros elsewhere

### Calculate the eigenvalues of any pauli matrix
https://en.wikipedia.org/wiki/Pauli_matrices